# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /u/trosko/projects/motility/motility

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /u/trosko/projects/motility/motility

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /u/trosko/projects/motility/motility/CMakeFiles /u/trosko/projects/motility/motility/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /u/trosko/projects/motility/motility/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named motility

# Build rule for target.
motility: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motility
.PHONY : motility

# fast build rule for target.
motility/fast:
	$(MAKE) -f src/CMakeFiles/motility.dir/build.make src/CMakeFiles/motility.dir/build
.PHONY : motility/fast

#=============================================================================
# Target rules for targets named test-find-iupac

# Build rule for target.
test-find-iupac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-find-iupac
.PHONY : test-find-iupac

# fast build rule for target.
test-find-iupac/fast:
	$(MAKE) -f tests/CMakeFiles/test-find-iupac.dir/build.make tests/CMakeFiles/test-find-iupac.dir/build
.PHONY : test-find-iupac/fast

#=============================================================================
# Target rules for targets named test-find-literal

# Build rule for target.
test-find-literal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-find-literal
.PHONY : test-find-literal

# fast build rule for target.
test-find-literal/fast:
	$(MAKE) -f tests/CMakeFiles/test-find-literal.dir/build.make tests/CMakeFiles/test-find-literal.dir/build
.PHONY : test-find-literal/fast

#=============================================================================
# Target rules for targets named test-find-op

# Build rule for target.
test-find-op: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-find-op
.PHONY : test-find-op

# fast build rule for target.
test-find-op/fast:
	$(MAKE) -f tests/CMakeFiles/test-find-op.dir/build.make tests/CMakeFiles/test-find-op.dir/build
.PHONY : test-find-op/fast

#=============================================================================
# Target rules for targets named test-find-pwm

# Build rule for target.
test-find-pwm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-find-pwm
.PHONY : test-find-pwm

# fast build rule for target.
test-find-pwm/fast:
	$(MAKE) -f tests/CMakeFiles/test-find-pwm.dir/build.make tests/CMakeFiles/test-find-pwm.dir/build
.PHONY : test-find-pwm/fast

#=============================================================================
# Target rules for targets named test-sequence

# Build rule for target.
test-sequence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-sequence
.PHONY : test-sequence

# fast build rule for target.
test-sequence/fast:
	$(MAKE) -f tests/CMakeFiles/test-sequence.dir/build.make tests/CMakeFiles/test-sequence.dir/build
.PHONY : test-sequence/fast

#=============================================================================
# Target rules for targets named motility_ext

# Build rule for target.
motility_ext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motility_ext
.PHONY : motility_ext

# fast build rule for target.
motility_ext/fast:
	$(MAKE) -f python/CMakeFiles/motility_ext.dir/build.make python/CMakeFiles/motility_ext.dir/build
.PHONY : motility_ext/fast

#=============================================================================
# Target rules for targets named motility_py

# Build rule for target.
motility_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motility_py
.PHONY : motility_py

# fast build rule for target.
motility_py/fast:
	$(MAKE) -f python/CMakeFiles/motility_py.dir/build.make python/CMakeFiles/motility_py.dir/build
.PHONY : motility_py/fast

#=============================================================================
# Target rules for targets named motility_py_install

# Build rule for target.
motility_py_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motility_py_install
.PHONY : motility_py_install

# fast build rule for target.
motility_py_install/fast:
	$(MAKE) -f python/CMakeFiles/motility_py_install.dir/build.make python/CMakeFiles/motility_py_install.dir/build
.PHONY : motility_py_install/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... motility"
	@echo "... test-find-iupac"
	@echo "... test-find-literal"
	@echo "... test-find-op"
	@echo "... test-find-pwm"
	@echo "... test-sequence"
	@echo "... motility_ext"
	@echo "... motility_py"
	@echo "... motility_py_install"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

